server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          client:
#            RestTemplate: DEBUG

stury-center:
  name: ${STUDY_CENTER_NAME}
  path: ${STUDY_CENTER_NAME}/api/**
  uri: lb://${STUDY_CENTER_NAME}

payment-service:
  name: ${PAYMENT_SERVICE_NAME}
  path: ${PAYMENT_SERVICE_NAME}/api/**
  uri: lb://${PAYMENT_SERVICE_NAME}

logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5000}