server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
    loadbalancer:
      ribbon:
        enabled: false
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
#    cloud:
#      gateway:
#        globalcors:
#          corsConfigurations:
#            '[/**]':
#              allowedOrigins:
#                - "${GATEWAY_URL}"
#              allowedHeaders:
#                - Content-Type
#                - Authorization
#        routes:
#          - id: ${STUDY_CENTER_NAME}
#            uri: lb://${STUDY_CENTER_NAME}
#            predicates:
#              - Path=/api/**
#            filters:
#              - StripPrefix=1
#          - id: ${PAYMENT_SERVICE_NAME}
#            uri: lb://${PAYMENT_SERVICE_NAME}
#            predicates:
#              - Path=/payment/**
#            filters:
#              - StripPrefix=1

stury-center:
  name: ${STUDY_CENTER_NAME}
  path: ${STUDY_CENTER_NAME}/api/**
  uri: lb://${STUDY_CENTER_NAME}

payment-service:
  name: ${PAYMENT_SERVICE_NAME}
  path: ${PAYMENT_SERVICE_NAME}/api/**
  uri: lb://${PAYMENT_SERVICE_NAME}