//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.24 at 11:43:13 PM SAMT 
//


package com.epam.amorozov.paymentservice.soaps.payments;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amorozov.spring.ws.payments package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amorozov.spring.ws.payments
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetPaymentRequest }
     * 
     */
    public SetPaymentRequest createSetPaymentRequest() {
        return new SetPaymentRequest();
    }

    /**
     * Create an instance of {@link SetPaymentResponse }
     * 
     */
    public SetPaymentResponse createSetPaymentResponse() {
        return new SetPaymentResponse();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link GetPaymentByPaymentIdRequest }
     * 
     */
    public GetPaymentByPaymentIdRequest createGetPaymentByPaymentIdRequest() {
        return new GetPaymentByPaymentIdRequest();
    }

    /**
     * Create an instance of {@link GetPaymentByPaymentIdResponse }
     * 
     */
    public GetPaymentByPaymentIdResponse createGetPaymentByPaymentIdResponse() {
        return new GetPaymentByPaymentIdResponse();
    }

}
