//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.24 at 11:43:13 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.amorozov.com/spring/ws/payments", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epam.amorozov.paymentservice.soaps.payments;
