//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.24 at 09:29:41 PM SAMT 
//


package com.epam.amorozov.studycenter.soap.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.amorozov.studycenter.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.amorozov.studycenter.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPaymentByPaymentIdResponse }
     * 
     */
    public GetPaymentByPaymentIdResponse createGetPaymentByPaymentIdResponse() {
        return new GetPaymentByPaymentIdResponse();
    }

    /**
     * Create an instance of {@link GetPaymentByPaymentIdRequest }
     * 
     */
    public GetPaymentByPaymentIdRequest createGetPaymentByPaymentIdRequest() {
        return new GetPaymentByPaymentIdRequest();
    }

    /**
     * Create an instance of {@link SetPaymentResponse }
     * 
     */
    public SetPaymentResponse createSetPaymentResponse() {
        return new SetPaymentResponse();
    }

    /**
     * Create an instance of {@link SetPaymentRequest }
     * 
     */
    public SetPaymentRequest createSetPaymentRequest() {
        return new SetPaymentRequest();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

}
