//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.24 at 09:29:41 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.amorozov.com/spring/ws/payments", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epam.amorozov.studycenter.soap.model;
